# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HGCHO Blog
email: hgcho84.kr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Studying
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hyegeuncho.github.io" # the base hostname & protocol for your site
github_username:  HyegeunCho

# Build settings
markdown: kramdown
# 페이지 당 n 개의 포스트를 보여준다
paginate: 1 

gems:
  - jekyll-paginate
